import fb.ContiguousSubArrays
import fb.PairSum
import fb.ReverseToMakeEqual
import fb.RotationalCipher

fun Collection<Problem>.runAll() = onEach { it.run() }
val lc = hashSetOf(
    AccountsMerge,
    AddStrings,
    AddTwoNumbers,
    AlienDictionary,
    BasicCalculatorII,
    BinarySearchTree,
    BinaryTreeTraversal,
    CakeArea,
    ClimbingStairs,
    CloneGraph,
    Combinations,
    CountingIslands,
    DailyTemperature,
    DecodeString,
    DecodeWays,
    Fibonacci,
    FizzBuzz,
    FloodFill,
    GameOfLife,
    GenerateParentheses,
    HIndex,
    KClosest,
    KClosestElements,
    KnightMoves,
    KthLargestNumber,
    LRUCache,
    LargestRectangle,
    LengthOfLongestSubstring,
    LetterCombinations,
    LevelOrder,
    LoggerRateLimiter,
    LongestCommonPrefix,
    LongestStringChain,
    LowestCommonAncestor,
    MedianOfTwoSortedArrays,
    MeetingRooms,
    MeetingRoomsII,
    MergeIntervals,
    MergeSort,
    MergeSortedArray,
    MergeTwoLists,
    MinParenthesesRemoval,
    MissingNumber,
    MissingPositive,
    MostVisitedPattern,
    MoveZeroes,
    MyCalendar,
    NQueensII,
    NumPairsDivisibleBy60,
    OpenLock,
    PathSum,
    PascalsTriangle,
    PerfectSquares,
    Permutation,
    PivotIndex,
    PowXN,
    ProductOfArrayExceptSelf,
    QuickSort,
    RandomIndexWithWeight,
    RandomizedSet,
    ReverseLinkedList,
    Roomba,
    RoomsAndGates,
    RotateImage,
    SameTree,
    SearchRotatedSortedArray,
    SpiralMatrix,
    StockBuySell,
    StringCompression,
    SubArraySum,
    SubdomainVisits,
    SudokuSolver,
    TargetSum,
    ThreeSum,
    TimeMap,
    TopKFrequent,
    TopKFrequentWords,
    TwoDMatrixSearchII,
    TwoSums,
    UglyNumberII,
    UndergroundSystem,
    ValidPalindrome,
    ValidPalindromeII,
    ValidParentheses,
    ValidSquare,
    ValidateBinarySearchTree,
    WordBreak,
    WordSearch
)

val fb = hashSetOf(ContiguousSubArrays, PairSum, ReverseToMakeEqual, RotationalCipher)

val problems = lc + fb